bind f display-popup -E "$HOME/.dotfiles/stow/tmux-sessionizer/.local/bin/tmux-sessionizer"

# this kill the current session and swithces to another one, if there is only one session it kills the server
bind X run-shell "[ $(tmux ls | wc -l) -eq 1 ] && tmux kill-server || tmux switch-client -l && tmux kill-session -a"

set -g status-left-length 300
set -g status-justify absolute-centre
set -g renumber-windows on
