bind f display-popup -E "$HOME/.local/bin/tmux-sessionizer"

set -s command-alias[100] kill-session-and-switch='run-shell "$HOME/.local/bin/tmux-sessionizer -s -k"'
set -s command-alias[101] save-session='run-shell "$HOME/.local/bin/tmux-sessionizer -s"'

bind X confirm-before -p "Kill current session? (y/n)" kill-session-and-switch
bind S confirm-before -p "Save current session? (y/n)" save-session
bind C-x confirm-before -p "Kill tmux server? (y/n)" 'run-shell "tmux list-sessions -F "#S" | grep -vF "default" | xargs -I {} tmux kill-session-and-switch"'

set -g status-left-length 300
set -g status-justify absolute-centre
set -g renumber-windows on
