bind f display-popup -E "$HOME/.dotfiles/stow/tmux-sessionizer/.local/bin/tmux-sessionizer"

set -s command-alias[100] kill-session-and-switch='run-shell "tmux-sessionizer -k"'
bind X confirm-before -p "Kill current session? (y/n)" kill-session-and-switch
bind C-x confirm-before -p "Kill tmux server? (y/n)" kill-server

set -g status-left-length 300
set -g status-justify absolute-centre
set -g renumber-windows on
